server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: student.exchange
    queue: student.queue
    routingkey: student.routingkey